version: '3'

services:
  web:
    build: ./catalog
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/locallibrary
    ports:
      - '8000:8000'
    depends_on:
      - db
  db:
    image: mysql:5.7
    ports:
      - '3307:3306'
    environment:
      MYSQL_DATABASE: 'library'
      MYSQL_USER: 'django'
      MYSQL_PASSWORD: '228228228'
      MYSQL_ROOT_PASSWORD: '228228228'
    restart: always
    volumes:
      - ./db_django:/var/lib/mysql
